FROM golang:1.21.5-alpine
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /enchantech-codex ./src/main.go

EXPOSE 11001

# Run
CMD ["/enchantech-codex"]