version: '3'

services:
  db:
    image: mariadb:latest
    restart: always
    ports:
      - "11306:3306"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: '1'
      MARIADB_DATABASE: 'db'
      MARIADB_USER: 'admin'
      MARIADB_PASSWORD: '1234'
